Fix SLI prober when TLS is disabled for Redis
vshn/appcat pull request #124
Opened 2024-01-16 16:46 UTC by TheBigLee

## Summary

This PR fixes a bug, where the SLI prober fails on Redis if TLS is explicitely disabled.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [ ] Update tests.
- [ ] Link this PR to related issues.

2024-01-17 07:48 UTC, Kidswiss approved these changes

2024-01-17 08:26 UTC, wejdross requested changes
since this can break few things if touched, can You add a test case to cover that?

2024-01-19 07:35 UTC, Kidswiss requested changes

2024-01-19 07:35 UTC, Kidswiss commented on pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
> +		probe, err = probes.NewFailingProbe(vshnpostgresqlsServiceKey, inst.Name, inst.ObjectMeta.Labels[claimNamespaceLabel], errors.New("This probe should fail"))
```suggestion
		probe, err = probes.NewFailingProbe(vshnpostgresqlsServiceKey, inst.Name, inst.ObjectMeta.Labels[claimNamespaceLabel], err)
```

If you pass the actual error in here we get more context in the logs. "This probe should fail", will not be helpful when trying to debug something.

2024-01-19 07:35 UTC, Kidswiss commented on pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
> +		probe, err = probes.NewFailingProbe(vshnRedisServiceKey, inst.Name, inst.Namespace, errors.New("This probe should fail"))
Same here.

2024-01-22 09:05 UTC, wejdross approved these changes

2024-01-23 13:43 UTC, merged