Update target SLA in SLA Reporter
vshn/appcat pull request #34
Opened 2023-07-06 13:58 UTC by zugao

## Summary

* Short summary of what's included in the PR
* Give special note to breaking changes

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update tests.

2023-07-06 14:03 UTC, Kidswiss requested changes
Have you tested this? It looks like the labels in the query don't match up with what you specified in the prometheus rule.

2023-07-06 14:03 UTC, Kidswiss commented on pkg/slareport/prom.go
> +	slaQuery         = `sla:objective:ratio{sloth_id="{{SLOTHID}}"}`
You did not add the `sloth_id` to your recording rule. This metric will only have a `service` label.

2023-07-07 08:08 UTC, zugao commented
I updated the label in the component. Now it should match.

2023-07-07 08:23 UTC, Kidswiss approved these changes

2023-07-07 08:34 UTC, merged