Redis prober
vshn/appcat pull request #63
Opened 2023-08-21 11:14 UTC by wejdross

## Summary

* Adding Redis prober to sliexporter

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog
- [x] Update tests.
- [x] Link this PR to related issues.

2023-08-21 13:37 UTC, zugao requested changes
I tried the prober and it successfully exports redis metrics.

2023-08-21 13:47 UTC, wejdross commented on pkg/sliexporter/vshnpostgresql_controller/vshnpostgresql_controller.go
> +//+kubebuilder:rbac:groups="",resources=secrets,verbs=get;list;watch
this is important for VSHNPostgreSQL as it ensures correct RBAC, it's duplicated across Redis and PostgreSQL, but generator is quite clever and understands that correctly

2023-08-21 14:00 UTC, wejdross commented on pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
> +		InsecureSkipVerify: true,
If You try to connect without TLS it fails, if You configure TLS and set InsecureSkipVerify: false it fails with message from comment above, if You configure TLS, skip verification (different names), then it works, I just made it work, but I think we should take a look at root cause in separate story

2023-08-21 14:13 UTC, Kidswiss commented on pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
> +		InsecureSkipVerify: true,
@zugao I agree, the prober should connect via valid TLS if the connection requires it. The connection secret should contain all the information necessary to do that.

Why do you use `x509.NewCertPool()` on line 123? The credential secret should give you the ca as well under the `ca.crt` field. Maybe that's the root of your issue?

2023-08-22 08:45 UTC, wejdross commented on pkg/sliexporter/vshnredis_controller/vshnredis_controller.go
> +		InsecureSkipVerify: true,
fixed using this commit: https://github.com/vshn/component-appcat/pull/204

after that I was able to remove insecureSkipVerify flag as dns names matched

2023-08-22 08:46 UTC, wejdross commented on cmd/sliexporter.go
> +	// SLIProberCMD.Flags().BoolVar(&s.enableVSHNRedis, "vshn-redis", getEnvBool("APPCAT_SLI_VSHNREDIS"),
done :)

2023-08-22 14:40 UTC, zugao approved these changes
LGTM

2023-08-23 08:54 UTC, merged