Update GRPC dependency
vshn/appcat pull request #92
Opened 2023-10-26 08:43 UTC by zugao

## Summary

There's a high risk [vulnerability](https://github.com/advisories/GHSA-m425-mq94-257g) in our current grpc dependency library.

## Checklist

- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog

2023-10-26 08:51 UTC, wejdross requested changes
according to this: https://github.com/grpc/grpc-go/releases

we should update to even newer version to avoid another bug

2023-10-26 09:04 UTC, zugao commented
Updated to the latest version.

2023-10-26 15:35 UTC, TheBigLee approved these changes

2023-10-27 07:49 UTC, wejdross approved these changes
lgtm

2023-10-27 07:49 UTC, merged